testingGaussJordan: GaussJordan
	clear
	./GaussJordan

GaussJordan: combinations.cpp Gauss_Jordan.h Gauss_Jordan.cpp main.cpp Matrix.cpp Matrix.h Parser.cpp
	g++ combinations.cpp Gauss_Jordan.cpp Matrix.cpp Parser.cpp main.cpp -o GaussJordan -std=c++17